/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 backroom.glb -T -R 2048 -f png -t 
Files: backroom.glb [4.84MB] > /Users/fant/work/experiments/canonical-website/public/models/raw/backroom-transformed.glb [4.39MB] (9%)
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ligths: THREE.Mesh;
    ligths001: THREE.Mesh;
    ligths003: THREE.Mesh;
    walls003_Baked: THREE.Mesh;
    roof_grid_Baked: THREE.Mesh;
    roof003_Baked: THREE.Mesh;
    floor004_Baked: THREE.Mesh;
  };
  materials: {
    ["Material.058"]: THREE.MeshStandardMaterial;
    ["Material.059"]: THREE.MeshStandardMaterial;
    ["Material.060"]: THREE.MeshStandardMaterial;
    ["walls.003_Baked"]: THREE.MeshBasicMaterial;
    ["roof grid_Baked"]: THREE.MeshBasicMaterial;
    ["roof.003_Baked"]: THREE.MeshBasicMaterial;
    ["floor.004_Baked"]: THREE.MeshBasicMaterial;
  };
};

export function BackroomModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/backroom-transformed.glb",
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.ligths.geometry}
        material={materials["Material.058"]}
        position={[-8.981, 4.681, -8.96]}
      />
      <mesh
        geometry={nodes.ligths001.geometry}
        material={materials["Material.059"]}
        position={[-8.981, 4.681, -8.96]}
      />
      <mesh
        geometry={nodes.ligths003.geometry}
        material={materials["Material.060"]}
        position={[-8.981, 4.681, -8.96]}
      />
      <mesh
        geometry={nodes.walls003_Baked.geometry}
        material={materials["walls.003_Baked"]}
        position={[-8.981, 4.681, -8.96]}
      />
      <mesh
        geometry={nodes.roof_grid_Baked.geometry}
        material={materials["roof grid_Baked"]}
        position={[-8.981, 4.681, -8.96]}
      />
      <mesh
        geometry={nodes.roof003_Baked.geometry}
        material={materials["roof.003_Baked"]}
        position={[-8.981, 4.681, -8.96]}
      />
      <mesh
        geometry={nodes.floor004_Baked.geometry}
        material={materials["floor.004_Baked"]}
        position={[-8.981, 4.681, -8.96]}
      />
    </group>
  );
}

useGLTF.preload("/models/backroom-transformed.glb");
